name: Node.js CI

on:
  push:
    branches:
      - canary
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci, build, and test
      run: |
        npm ci
        npm run build
        npm test

  e2e:

    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install, build
      run: |
        npm ci
        npm run build
    - name: Setup WeChat DevTools
      uses: takashiro/setup-wechat-devtools@canary
      with:
        smtp-host: ${{ secrets.SMTP_HOST }}
        smtp-port: ${{ secrets.SMTP_HOST }}
        smtp-secure: true
        smtp-username: ${{ secrets.SMTP_USERNAME }}
        smtp-password: ${{ secrets.SMTP_PASSWORD }}
        smtp-sender: ${{ secrets.SMTP_SENDER }}
        smtp-receiver: ${{ secrets.SMTP_RECEIVER }}
    - name: Run end-to-end tests
      run: npm run jest-e2e
